// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBohErBoaMgLzveuCQ2FT3a8FiFlKOIpIM',
    appId: '1:459514121438:web:4b16d4205747abb390864f',
    messagingSenderId: '459514121438',
    projectId: 'waiapp-f2024',
    authDomain: 'waiapp-f2024.firebaseapp.com',
    storageBucket: 'waiapp-f2024.firebasestorage.app',
    measurementId: 'G-GW0CTC7K8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFEhCCKs3d3UlMQMdThIBk1fRvD2D7G4',
    appId: '1:459514121438:android:7aa44abbf0717dc990864f',
    messagingSenderId: '459514121438',
    projectId: 'waiapp-f2024',
    storageBucket: 'waiapp-f2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnpq3TMqXGK6rUeO7N5gemBjm0JrOOgYs',
    appId: '1:459514121438:ios:97f0f7bd6109b0da90864f',
    messagingSenderId: '459514121438',
    projectId: 'waiapp-f2024',
    storageBucket: 'waiapp-f2024.firebasestorage.app',
    androidClientId: '459514121438-nr19j9fv3bj2g3hfqh4l0eqqq9vr442v.apps.googleusercontent.com',
    iosClientId: '459514121438-9hsd4sfjj9cmhe9gjg8mtbr4cqh5mph4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnpq3TMqXGK6rUeO7N5gemBjm0JrOOgYs',
    appId: '1:459514121438:ios:97f0f7bd6109b0da90864f',
    messagingSenderId: '459514121438',
    projectId: 'waiapp-f2024',
    storageBucket: 'waiapp-f2024.firebasestorage.app',
    androidClientId: '459514121438-nr19j9fv3bj2g3hfqh4l0eqqq9vr442v.apps.googleusercontent.com',
    iosClientId: '459514121438-9hsd4sfjj9cmhe9gjg8mtbr4cqh5mph4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBohErBoaMgLzveuCQ2FT3a8FiFlKOIpIM',
    appId: '1:459514121438:web:fc0b8e0997af869490864f',
    messagingSenderId: '459514121438',
    projectId: 'waiapp-f2024',
    authDomain: 'waiapp-f2024.firebaseapp.com',
    storageBucket: 'waiapp-f2024.firebasestorage.app',
    measurementId: 'G-8X6KWW05MH',
  );
}
